name: LevelIsBorder
version: '${project.version}'
main: com.jannis.levelisborder.LevelIsBorder
api-version: 1.17
depend:
  - WorldBorderAPI
authors: [ Jannis ]
description: The Player Levels are the size of the border
commands:
  border:
    description: You can edit the border
    usage: /border command <arg1> (<arg2>)
